FROM alpine:latest

RUN apk --no-cache add \
    ca-certificates \
    curl \
    tar \
    xz \
    openssl \
    python3 \
    python3-pip

RUN pip3 install numpy

WORKDIR /app

COPY docker-project-dir /app

CMD ["./run.sh"]
