FROM nvcr.io/nvidia/merlin/merlin-pytorch:23.12
# FROM krogertechnology-docker.jfrog.io/merlin-pytorch:23.12

# Add the requirements.txt file

COPY requirements-build.txt ./requirements-build.txt

# Provide Arguments
ARG ART_SAAS_USER
ARG PYPI_IDENTITY_TOKEN

# install the requirements
RUN mkdir -p ~/.pip 
RUN ls -al ~/.pip 
RUN echo "[global]" > ~/.pip/pip.conf 
RUN echo "index-url = https://${ART_SAAS_USER}:${PYPI_IDENTITY_TOKEN}@krogertechnology.jfrog.io/artifactory/api/pypi/8451-python-remote/simple" >> ~/.pip/pip.conf
RUN echo "extra-index-url = https://pypi.org/simple" >> ~/.pip/pip.conf
RUN echo "$(<~/.pip/pip.conf)"
RUN cat ~/.pip/pip.conf
RUN pip3 install --verbose -r requirements-build.txt