name: Build Docker Image

on:
  push:
    branches:
      # - main
      - feature/merlin-pytorch-build
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ART_SAAS_USER:
        required: true
      JFROG_SAAS_TOKEN_VALUE:
        required: true
      PYPI_IDENTITY_TOKEN:
        required: true

env:
  DOCKER_REGISTRY: krogertechnology-docker-test.jfrog.io
  DOCKER_FILE: ./DockerFile
  ART_SAAS_USER: ${{ secrets.ART_SAAS_USER }}
  JFROG_SAAS_TOKEN_VALUE: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}
  PYPI_IDENTITY_TOKEN: ${{ secrets.PYPI_IDENTITY_TOKEN }}
  DOCKER_IMAGE_NAME: pzn-reco-sys/merlin-pytorch

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    name: Build-Docker-Image

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ART_SAAS_USER }}
          password: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}
      - name: Build and push Docker Image
        run: |
          echo "starting now"
          echo "Building Docker image ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}"
          docker build -f "${{ env.DOCKER_FILE }}" --build-arg ART_SAAS_USER=${{ secrets.ART_SAAS_USER }} --build-arg PYPI_IDENTITY_TOKEN=${{ secrets.PYPI_IDENTITY_TOKEN }} -t "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}" .
          # docker push "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}"
