name: Build Docker Image

on:
  push:
    branches:
      # - release/build
      - bugfix/*
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ART_SAAS_USERNAME:
        required: true
      JFROG_SAAS_TOKEN_VALUE:
        required: true
      PYPI_IDENTITY_TOKEN:
        required: true

env:
  DOCKER_REGISTRY: krogertechnology-docker-test.jfrog.io
  DOCKER_FILE: ./dockerfile
  ART_SAAS_USERNAME: ${{ secrets.ART_SAAS_USERNAME }}
  JFROG_SAAS_TOKEN_VALUE: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}
  PYPI_IDENTITY_TOKEN: ${{ secrets.PYPI_IDENTITY_TOKEN }}
  DOCKER_IMAGE_NAME: pzn-reco-sys/merlin-pytorch

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    name: Build-Docker-Image

    steps:
      - name: clear unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet \
          && sudo rm -rf /opt/ghc \
          && sudo rm -rf "/usr/local/share/boost" \
          && sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ART_SAAS_USERNAME }}
          password: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}
      # - name: Semantic Versioning
      #   uses: anothrNick/github-tag-action@1.67.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: patch
      #     RELEASE_BRANCHES: "release/build"
      #     REPO_OWNER: krogertechnology
      - name: Manual Semantic Versioning
        run: echo "VERSION=0.0.1-base" >> $GITHUB_ENV
      - name: Build and push Docker Image
        run: |
          echo "starting now"
          echo "Building Docker image ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$VERSION"
          # VERSION=$(git describe --tags --abbrev=0)
          docker build -f "${{ env.DOCKER_FILE }}" --build-arg ART_SAAS_USERNAME=${{ secrets.ART_SAAS_USERNAME }} --build-arg PYPI_IDENTITY_TOKEN=${{ secrets.PYPI_IDENTITY_TOKEN }} -t "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$VERSION" .
          docker push "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$VERSION"