name: '🐳 🏗 Build Docker Image'

on:
  push:
    branches: [ "main", "feature-docker-build" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v3

      - name: Login to Jfrog
        uses: docker/login-action@v2
        with:
          registry: krogertechnology-docker.jfrog.io
          username: ${{ secrets.ART_SAAS_USER }}
          password: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}

      - name: Build and Run Docker
        run: |
          docker build -t krogertechnology-docker.jfrog.io/docker-test/docker-test/alpine:${{ github.sha }} -f Dockerfile .
          docker push krogertechnology-docker.jfrog.io/docker-test/docker-test/alpine:${{ github.sha }}
        env:
          JFROG_USERNAME: ${{ secrets.ART_SAAS_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_SAAS_TOKEN_VALUE }}
