name: Jfrog Login Auth workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
      - name: Test Jfrog CLI
        run: |
          jf rt ping --url=https://krogertechnology.jfrog.io/artifactory --access-token ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Pull Docker Image from Artifactory
        run: |
          jf rt docker-pull docker-remote/alpine:latest --url=https://krogertechnology.jfrog.io/artifactory/ --access-token ${{ secrets.JF_ACCESS_TOKEN }}
  
      - name: Verify Docker Image Pull
        run: |
          docker images | grep alpine:latest
